name: Daily Commit

on:
  schedule:
    # Runs every day at 08:05 UTC (change to any specific time you want)
    - cron: '5 8 * * *'
  workflow_dispatch:  # for manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify file for daily commit - 21f3001750@ds.study.iitm.ac.in
        run: |
          echo "Commit on $(date)" >> daily-log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit on $(date)"
          git push
